<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reviews = [
            "I love this course. It's very helpful for me.",
            "I'm very satisfied with this course.",
            'This course exceeded my expectations.',
            'The content is well-organized and easy to follow.',
            'I learned a lot from this course.',
            'The instructor is very knowledgeable.',
            'I would recommend this course to others.',
            'Great course with practical examples.',
            'The explanations are clear and concise.',
            'I appreciate the hands-on approach.',
            'This course is worth every penny.',
            'The assignments are challenging but rewarding.',
            'I feel more confident in my skills after taking this course.',
            'The course material is up-to-date.',
            'The instructor is very engaging.',
            'I enjoyed the interactive elements of the course.',
            'The course is very comprehensive.',
            'I like the step-by-step approach.',
            'The course is well-paced.',
            'The instructor provides great feedback.',
            'I learned new techniques that I can apply to my work.',
            'The course is very informative.',
            'I appreciate the real-world examples.',
            'The course is easy to understand.',
            'The instructor is very supportive.',
            'I like the practical exercises.',
            'The course is very detailed.',
            'The instructor is very responsive to questions.',
            'I feel more prepared for my job after taking this course.',
            'The course is very engaging.',
            'I like the variety of topics covered.',
            'The instructor is very clear in his explanations.',
            'The course is very well-structured.',
            'I appreciate the additional resources provided.',
            'The course is very interactive.',
            'The instructor is very passionate about the subject.',
            'I learned a lot of new information.',
            'The course is very thorough.',
            'I like the real-world applications of the material.',
            'The instructor is very experienced.',
            'The course is very practical.',
            'I appreciate the step-by-step instructions.',
            'The course is very user-friendly.',
            'The instructor is very approachable.',
            'I like the hands-on projects.',
            'The course is very well-explained.',
            'I appreciate the detailed explanations.',
            'The course is very helpful.',
            'The instructor is very professional.',
            'I like the clear and concise instructions.',
            'The course is very easy to follow.',
            'I appreciate the practical examples.',
            'The course content is very relevant to my job.',
            "I appreciate the instructor's enthusiasm.",
            'The course has a good balance of theory and practice.',
            'I like the way the course is structured.',
            "The instructor's explanations are very clear.",
            'The course is very engaging and informative.',
            'I learned a lot of practical skills.',
            'The course is very well-organized.',
            "I appreciate the instructor's expertise.",
            'The course is very easy to understand.',
            'I like the interactive nature of the course.',
            'The course is very comprehensive and detailed.',
            'I appreciate the real-world applications.',
            'The course is very well-paced.',
            "I like the instructor's teaching style.",
            'The course is very informative and helpful.',
            'I appreciate the practical approach.',
            'The course is very user-friendly and easy to follow.',
            'I like the hands-on exercises.',
            'The course is very well-explained and detailed.',
            "I appreciate the instructor's feedback.",
            'The course is very thorough and comprehensive.',
            'I like the step-by-step instructions.',
            'The course is very engaging and interactive.',
            "I appreciate the instructor's support.",
            'The course is very practical and useful.',
            'I like the clear and concise explanations.',
            'The course is very well-structured and organized.',
            'I appreciate the additional resources provided.',
            'The course is very informative and engaging.',
            'I like the real-world examples.',
            'The course is very detailed and thorough.',
            "I appreciate the instructor's responsiveness.",
            'The course is very helpful and practical.',
            'I like the hands-on approach.',
            'The course is very well-paced and easy to follow.',
            "I appreciate the instructor's knowledge.",
            'The course is very comprehensive and informative.',
            'I like the practical exercises.',
            'The course is very user-friendly and engaging.',
            "I appreciate the instructor's passion.",
            'The course is very well-explained and easy to understand.',
            'I like the real-world applications.',
            'The course is very thorough and detailed.',
            "I appreciate the instructor's expertise and knowledge.",
            'The course is very practical and informative.',
            'I like the step-by-step approach.',
            'The course is very engaging and easy to follow.',
            "I appreciate the instructor's support and feedback.",
            'The course is very comprehensive and useful.',
            'The course content is very well thought out. I found it extremely beneficial.',
            "The instructor's teaching methods are excellent. I learned a lot.",
            'The course is very engaging. The material is presented in a clear and concise manner.',
            "I appreciate the instructor's dedication. The course is very informative.",
            'The course is very well-structured. I found it easy to follow.',
            'The instructor is very knowledgeable. The course content is very relevant.',
            'I like the practical approach of the course. It helped me understand the concepts better.',
            'The course is very detailed. I appreciate the thorough explanations.',
            'The instructor is very responsive. The course is very interactive.',
            'I learned a lot from this course. The practical examples were very helpful.',
            'The course is very comprehensive. I appreciate the step-by-step instructions.',
            'The instructor is very engaging. The course is very well-paced.',
            'I like the hands-on projects. They helped me apply what I learned.',
            "The course is very informative. The instructor's explanations are very clear.",
            'I appreciate the real-world applications. The course is very practical.',
            'The course is very well-organized. I found it easy to follow.',
            'The instructor is very passionate. The course is very engaging.',
            'I learned a lot of new skills. The course is very practical.',
            'The course is very user-friendly. The material is easy to understand.',
            "I appreciate the instructor's feedback. The course is very helpful.",
            'The course is very thorough. I like the detailed explanations.',
            'The instructor is very professional. The course is very well-explained.',
            'I like the interactive elements of the course. They made learning fun.',
            'The course is very comprehensive. I appreciate the additional resources provided.',
            'The instructor is very supportive. The course is very engaging.',
            'I learned a lot from this course. The practical exercises were very helpful.',
            'The course is very well-paced. I found it easy to keep up.',
            'The instructor is very knowledgeable. The course content is very relevant.',
            'I like the step-by-step approach. It made learning easier.',
            "The course is very informative. The instructor's explanations are very clear.",
            'I appreciate the real-world examples. The course is very practical.',
            'The course is very well-structured. I found it easy to follow.',
            'The instructor is very engaging. The course is very well-paced.',
            'I like the hands-on projects. They helped me apply what I learned.',
            "The course is very informative. The instructor's explanations are very clear.",
            'I appreciate the real-world applications. The course is very practical.',
            'The course is very well-organized. I found it easy to follow.',
            'The instructor is very passionate. The course is very engaging.',
            'I learned a lot of new skills. The course is very practical.',
            'The course is very user-friendly. The material is easy to understand.',
            "I appreciate the instructor's feedback. The course is very helpful.",
            'The course is very thorough. I like the detailed explanations.',
            'The instructor is very professional. The course is very well-explained.',
            'I like the interactive elements of the course. They made learning fun.',
            'The course is very comprehensive. I appreciate the additional resources provided.',
            'The instructor is very supportive. The course is very engaging.',
            'I learned a lot from this course. The practical exercises were very helpful.',
            'The course is very well-paced. I found it easy to keep up.',
            'The instructor is very knowledgeable. The course content is very relevant.',
            'I like the step-by-step approach. It made learning easier.',
            "The course is very informative. The instructor's explanations are very clear.",
        ];

        foreach ($reviews as $review) {
            \App\Models\Review::factory()->create([
                'content' => $review,
            ]);
        }
    }
}
